site:
  title: "Open Manufacturing Platform - Semantic Data Structuring Working Group"
  url: https://openmanufacturingplatform.github.io/sds-documentation/
  start_page: sds-documentation::index.adoc
content:
  sources:
     - url: .
       branches: HEAD
       tags: '*'
       start_path: src/docs
     - url: https://github.com/OpenManufacturingPlatform/sds-bamm-aspect-meta-model
       branches: HEAD
       tags: '*'
       start_path: src/docs
     - url: https://github.com/OpenManufacturingPlatform/sds-sdk
       branches: HEAD
       tags: '*'
       start_path: documentation/developer-guide
ui:
  bundle:
    url: https://github.com/OpenManufacturingPlatform/sds-antora-ui/releases/download/v1.0.0/sds-antora-ui-bundle-1.0.0.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
runtime:
  cache_dir: ./.cache/antora
asciidoc:
  attributes:
    doctype: book
    sectanchors: true
    idprefix: ''
    idseparator: '-'
    stem: 'asciimath'
    ok: 'icon:check-circle[role="green",size="2x"]'
    nok: 'icon:times-circle[role="red",size="2x"]'
    meta-model-version: 1.0.0@
    meta-model-full-name: BAMM Aspect Meta Model
    meta-model-abbr: BAMM
    omp: Open Manufacturing Platform
    omp-abbr: OMP
    bamm: urn:bamm:io.openmanufacturing:meta-model:1.0.0#@
    bamm-c: urn:bamm:io.openmanufacturing:characteristic:1.0.0#@
    bamm-e: urn:bamm:io.openmanufacturing:entity:1.0.0#@
    unit:  urn:bamm:io.openmanufacturing:unit:1.0.0#@
    aspect-meta-model-version: '1.0.0'
    sds-sdk-version: '1.0.2'
    example-ns: com.mycompany@

