name: Antora Build
on:
  push:
    branches:
    - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        ref: main
        fetch-depth: '0'
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Antora
      run: npm i -g @antora/cli@2.3 antora-site-generator-lunr
    - name: Fetch and Build Antora site
      run: antora --fetch site.yml --generator antora-site-generator-lunr --stacktrace   
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: build/site